workflows:
  build:
    name: Build APK
    environment:
      flutter: 3.19.6
    scripts:
      - flutter clean
      - sed -i 's/sdk: ">=3.6.1 <4.0.0"/sdk: ">=3.0.0 <4.0.0"/g' pubspec.yaml
      - flutter pub get
      - flutter build apk --release --android-skip-build-dependency-validation
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
